apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - name: nginx
    image: nginx:1.13
  - name: nginx
    image: nginx:1.13
  resources:
    requests:
      storage.kubernetes.io/overlay: 256Mi
    limits:
      storage.kubernetes.io/overlay: 512Mi
