apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-local-pv
  annotations:
   "volume.alpha.kubernetes.io/node-affinity": '{
     "requiredDuringSchedulingIgnoredDuringExecution": {
       "nodeSelectorTerms": [
         { "matchExpressions": [
           { "key": "kubernetes.io/hostname",
             "operator": "In",
             "values": ["my-node"]
           }
         ]}
        ]}
       }'
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /dev/loop0
  volumeType: block
