apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: simple-deployment
    spec:
      containers:
      - name: nginx
        image: nginx:1.13
        ports:
        - containerPort: 80
        env:
          - name: ADDRESS
            value: https://google.com
          - name: ANOTHER_ADDRESS
            value: https://facebook.com
