apiVersion: v1
kind: Pod
metadata:
  name: backend-standalone
  labels:
    app: "nginx-standalone"
spec:
  containers:
  - name: nginx
    image: nginx:1.13
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-standalone
spec:
  selector:
    app: "nginx-standalone"
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-standalone
spec:
  containers:
  - name: busybox
    image: busybox:1.24
    command:
    - /bin/sh
    - -c
    - while true; do sleep 1; done
