apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: "nginx"
spec:
  containers:
  - name: nginx
    image: nginx:1.13
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: "nginx"
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: busybox
    image: busybox:1.24
    command:
    - /bin/sh
    - -c
    - while true; do wget -qO- nginx; sleep 1; done
