apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: usersvc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: usersvc
    spec:
      containers:
      - name: usersvc
        image: usersvc:v2
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: usersvc
  name: usersvc
spec:
  type: ClusterIP
  ports:
  - name: usersvc
    port: 80
  selector:
    service: usersvc
