kind: Pod
apiVersion: v1
metadata:
  name: mypod
spec:
  containers:
    - name: nginx
      image: nginx:1.13
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypath
    - name: busybox
      image: busybox:1.26
      command: ["sh", "-c", "sleep 12000"]
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypath
  volumes:
    - name: mypath
      hostPath:
        path: /tmp/data
