apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: k8s.io/minikube-hostpath
allowVolumeExpand: false
