# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end

  config.vm.define "master" do |node|
    node.vm.hostname = "master"
    node.vm.network :private_network, ip: "192.168.66.10"
    node.vm.provision :shell, inline: "sed 's/127\.0\.0\.1.*master.*/192\.168\.66\.10 master/' -i /etc/hosts"
  end

  config.vm.define "node1" do |node|
    node.vm.hostname = "node1"
    node.vm.network :private_network, ip: "192.168.66.20"
    node.vm.provision :shell, inline: "sed 's/127\.0\.0\.1.*node1.*/192\.168\.66\.20 node1/' -i /etc/hosts"
  end

  config.vm.define "node2" do |node|
    node.vm.hostname = "node2"
    node.vm.network :private_network, ip: "192.168.66.30"
    node.vm.provision :shell, inline: "sed 's/127\.0\.0\.1.*node2.*/192\.168\.66\.30 node2/' -i /etc/hosts"
  end
end
