apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment-svc
spec:
  replicas: 3
  template:
    metadata:
      labels:
        nginx: multiple
    spec:
      containers:
      - name: nginx
        image: nginx:1.13
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-multiple
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    nginx: multiple
