#+STARTUP: overview
#+STARTUP: hideblocks

* runtime spec (03/18/2017, v1.0.0-rc5)
** Overview
   https://github.com/opencontainers/runtime-spec
   oci runtime spec is a specification that defines what a software container is
   and its attributes in a cross platform way. runc is an implementation of the
   specification. Use cases targeted by this spec:
    - Application bundle builder
      Application bundle builder is the person who wants to create containers. He
      or she defines bundle information that conforms to runtime spec, then feed
      the information to any runtime implementation to launch a container.
    - Hook Developers
      Hook developers can extend the functionality of an OCI-compliant runtime by
      hooking into a container's lifecycle with an external application. Example
      use cases include sophisticated network configuration, volume garbage
      collection, etc.
    - Runtime Developers
      Runtime developers can build runtime implementations that run OCI-compliant
      bundles and container configuration, containing low-level OS and host specific
      details, on a particular platform.
** Details
   The content of runtime spec is three fold:
   - Filesystem bundle
     At its heart, it defines the directory structure that application bundle builder
     must conform so that runtime can extract information. It consists of:
     - config.json : contains configuration data.
     - A directory representing the root filesystem of the container.
   - Runtime and lifecycle
     Runtime and lifecycle defines operations that can be performed on OCI-compliant
     container, e.g. start, kill. In addition to operations, it also defines error
     handling, hooks, container state management. Runtime is platform specific: there
     is a general one, with platform additions on top of it.
   - Configuration
     The configuration file contains metadata necessary to implement standard operations
     against the container. Configuration is also platform specific: a general config
     across all platforms, with platform additions on top of it. General configuration
     contains things like hostname, container root path, container hooks, oci version,
     process information, etc. For linux specific configuration, there is namespace,
     cgroups, mount propagation options, etc.
* image spec (03/18/2017, v1.0.0-rc5)
** Overview
   This specification defines how to create an OCI Image, which will generally be
   done by a build system, and output an image manifest, a filesystem serialization,
   and an image configuration. The runtime specification above outlines how to run
   a "filesystem bundle" that is unpacked on disk. At a high-level an OCI implementation
   would download an OCI Image then unpack that image into an OCI Runtime filesystem
   bundle. At this point the OCI Runtime bundle would be run by an OCI Runtime. The
   combination of the image manifest, image configuration, and one or more filesystem
   serializations is called the "OCI Image". Once built, the OCI Image can then be
   discovered by name, downloaded, verified by hash, trusted through a signature,
   and unpacked into an OCI Runtime Bundle. At a high level:
    - Image manifest contains metadata about the contents and dependencies of the
      image including the content-addressable identity of one or more filesystem
      serialization archives that will be unpacked to make up the final runnable
      filesystem.
    - Filesystem serialization contains the actual content. It contains things like
      layer, diff, etc; similar to docker term.
    - Image configuration includes information such as application arguments,
      environments, etc.
   https://github.com/opencontainers/image-spec
** Example
   https://github.com/opencontainers/image-tools
* oci specs expriments (03/18/2017, v1.0.0-rc5)
** Tools
  There are a few tools used here:
   - https://github.com/projectatomic/skopeo
   - https://github.com/opencontainers/image-tools
** Build and work with skopeo
   `skopeo` is a command line utility for various operations on container images
   and image repositories. Recent version doesn't build properly, we have to switch
   to older version (v0.1.17), then build it using `make binary-local`.
     #+BEGIN_SRC sh
     $ git checkout v0.1.17
     & sudo apt-get install go-md2man libgpgme11-dev libassuan-dev
     $ make binary-local && sudo mv skopeo /usr/local/bin
     $ skopeo inspect docker://docker.io/busybox
     #+END_SRC
   `skopeo inspect` command is a simple wrapper of https://github.com/containers/image.
   Now translate docker image to oci layout. Internally, skopeo also depends on
   'containers/image' project. The project abstract different image specification
   into a `Image` interface; the copy operation is accomplished by copying layer
   by layer.
     #+BEGIN_SRC sh
     $ cd ~
     $ skopeo copy docker://busybox:latest oci:busybox-oci
     #+END_SRC
** Build and work with image-tools
   The image-tools is a collection of tools for working with OCI image format
   sepc. In release v0.1.0, there are multiple commands; it was then merged into
   a single command (working on commit 1f4874510501730a417a7137ccae21582985c793).
   Now that we have the busybox oci layout (~/busybox_ocilayout), we can use
   image-tools to create runtime bundle, i.e. from oci image spec to runtime
   bundle; this can be achieved via command:
     #+BEGIN_SRC sh
       $ oci-image-tool create --ref latest busybox-oci busybox-bundle
     #+END_SRC
   Now we can use `runc` to create container based on the runtime bundle.
** Create container using runc
   Now build runc (working on commit c266f1470c25d9001a133000123e89f0a59d0571):
     #+BEGIN_SRC sh
       $ make && sudo make install
     #+END_SRC
   Based on image-tools documentation, we should be able to run container with:
     #+BEGIN_SRC sh
       $ cd busybox-bundle && sudo runc run busybox
     #+END_SRC
   But this doesn't work for me (ubuntu 14.04 virtualbox). However, using
   unpack works:
     #+BEGIN_SRC sh
       $ rm -rf busybox-bundle
       $ oci-image-tool unpack --ref latest busybox-oci rootfs
       $ mkdir busybox && mv rootfs busybox
       $ cd busybox && runc spec
       $ sudo runc run busybox
     #+END_SRC
** Other projects
   `umoci` is another project to modify oci image, see its README.
