apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity-2
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - 127.0.0.1
            - 127.1.1.1
  containers:
  - name: with-node-affinity-1
    image: nginx:1.13
