apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity-4
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - 127.0.0.1
      - weight: 10
        preference:
          matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - 192.168.33.33
  containers:
  - name: with-node-affinity-4
    image: nginx:1.13
