kind: Pod
apiVersion: v1
metadata:
  name: nginx
  namespace: training
  labels:
    app: nginx
    ns: training
spec:
  containers:
    - name: nginx
      image: nginx:1.13
---
kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: training
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: nginx
    ns: training
