kind: Pod
apiVersion: v1
metadata:
  namespace: training
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.13
    resources:
      requests:
        cpu: "100m"
        memory: "64Gi"
      limits:
        cpu: "100m"
        memory: "64Gi"
