kind: Pod
apiVersion: v1
metadata:
  name: nginx-without
spec:
  containers:
    - name: nginx
      image: nginx:1.13




# 1. create taints `kubectl taint nodes 127.0.0.1 dedicated=banana:NoSchedule`
# 2. explain 'NoSchedule'
