kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi


# 1. create and inspect pvc; pvc is pending
# 2. explain selector and storageclass
