apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv
  labels:
    hostpath: "true"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data


# create and inspect persistent volume (hostpath just for testing)
