apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    nginx: "true"
spec:
  containers:
    - name: nginx
      image: nginx:1.13
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    nginx: "true"
