apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeport
  labels:
    nginx: "true"
spec:
  containers:
    - name: nginx
      image: nginx:1.13
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-nodeport
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 32111
  selector:
    nginx: "true"
