apiVersion: v1
kind: Pod
metadata:
  name: pod-label-1
  labels:
    environment: test
    tier: backend
    track: weekly
spec:
  containers:
  - name: pod-label
    image: nginx:1.13
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-label-2
  labels:
    environment: test
    tier: frontend
    track: weekly
spec:
  containers:
  - name: pod-label
    image: nginx:1.13
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-label-3
  labels:
    environment: prod
    tier: frontend
    track: weekly
spec:
  containers:
  - name: pod-label
    image: nginx:1.13
